### ISSUE TITLE
Broken POST at v0.9.3

### ISSUE THREAD

**Issue by joebalancio** [mio/mongo#7]
```
/mnt/BC/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:245
        throw message;
              ^
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/mnt/models/node_modules/mio-mongo/node_modules/mongodb/node_modules/bson/lib/bson/objectid.js:38:11)
    at prepareQueryOrDocument (/mnt/models/node_modules/mio-mongo/lib/mio-mongo.js:1008:30)
    at Function.exports.findOne (/mnt/models/node_modules/mio-mongo/lib/mio-mongo.js:211:20)
    at next (/mnt/models/node_modules/mio/lib/resource.js:1065:21)
    at Function.Resource.trigger (/mnt/models/node_modules/mio/lib/resource.js:1094:3)
    at Function.Resource.get (/mnt/models/node_modules/mio/lib/resource.js:490:15)
    at Query.exec (/mnt/models/node_modules/mio/lib/query.js:302:18)
    at Function.checkForExistingAnswer (/mnt/models/lib/resources/prequals/Answer.js:143:6)
    at next (/mnt/models/node_modules/mio/lib/resource.js:1065:21)
    at Function.<anonymous> (/mnt/models/lib/resources/prequals/Answer.js:135:5)
```

**Comment by alexmingoia** [comment]
Does the attribute on the Answer resource have `objectId: true`? If so, that's the problem. mio-mongo will cast any attribute with `objectId: true` as an ObjectID.

**Comment by joebalancio** [comment]
@alexmingoia I think I know what the problem is. I'm saying that an answer belongs to a question where the foreign key is questionId, but an answer's questionId does not neccesarily have to be an object id.

**Comment by joebalancio** [comment]
The query in one of my hooks was messed up and was passing in a regular string for an id.
