### ISSUE TITLE
Error when using nested true on attribute that has no nested attributes

### ISSUE THREAD

**Issue by joebalancio** [mio/mongo#8]
```
/mnt/models/node_modules/mio-mongo/node_modules/mongodb/node_modules/bson/lib/bson/objectid.js:38
    throw new Error("Argument passed in must be a single String of 12 bytes or
          ^
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/mnt/models/node_modules/mio-mongo/node_modules/mongodb/node_modules/bson/lib/bson/objectid.js:38:11)
    at prepareQueryOrDocument (/mnt/models/node_modules/mio-mongo/lib/mio-mongo.js:1008:30)
    at prepareQueryOrDocument (/mnt/models/node_modules/mio-mongo/lib/mio-mongo.js:1003:30)
    at prepareQueryOrDocument (/mnt/models/node_modules/mio-mongo/lib/mio-mongo.js:1003:30)
    at /mnt/models/node_modules/mio-mongo/lib/mio-mongo.js:427:15
    at fn (/mnt/models/node_modules/mio-mongo/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/mnt/models/node_modules/mio-mongo/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by alexmingoia** [comment]
Fixed with `mio-mongo@0.9.9`.
